version: '3'

services:
  mysql-docker-container:
    hostname: "db"
    build:
      context: . 
      dockerfile: mysqldb.dockerfile
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_locadora
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - /data/mysql
    container_name: mysql-docker-container
    networks:
        - app_net

  rabbit-docker-container:
    image: "rabbitmq:3"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
     - $PWD/storage/rabbit1:/var/lib/rabbitmq
    container_name: rabbit-docker-container
    networks:
        - app_net
        
  spring-boot-jpa-locadora:
    image: spring-boot-jpa-locadora-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
      - rabbit1
    ports:
      - 8087:8080
    volumes:
      - /data/spring-boot-app
    container_name: rabbit-docker-container
    networks:
        - app_net
        