FROM java:8
LABEL maintainer=“fabio.kuroda@gmail.com”
EXPOSE 8080
ADD /LocadoraCarros-0.0.1-SNAPSHOT.jar LocadoraCarros-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","LocadoraCarros-0.0.1-SNAPSHOT.jar"]